services:
  ais_db_psql:
    image: postgres:14.2-alpine
    container_name: postgres_ais
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ais_db
    networks:
      - ais_network
    volumes:
      - ais_volume:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: postgres_adminer_ais
    ports:
      - '8080:8080'
    environment:
      ADMINER_DESIGN: pepa-linha
    networks:
      - 'ais_network'
    depends_on:
      - ais_db_psql

networks:
  ais_network: {}

volumes:
  ais_volume: {}
