services:
  postgres_ais:
    image: postgres:14.2-alpine
    container_name: postgres_ais
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres_ais
    networks:
      - ais_network
    volumes:
      - ais_volume:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: postgres_adminer_ais
    ports:
      - 9191:8080
    environment:
      ADMINER_DESIGN: pepa-linha
    networks:
      - ais_network
    depends_on:
      - postgres_ais

  # ais_be:
  #   build: .
  #   image: ais_be:1.0.0
  #   container_name: ais_be
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - ais_network
  #   environment:
  #     - psql.host=postgres_ais
  #   depends_on:
  #     - postgres_ais
  #   restart: unless-stopped

networks:
  ais_network: {}

volumes:
  ais_volume: {}
