name: Ais Be

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build Environment
        run: make composerestart

      - name: Golang Test
        run: make gotest

      - name: Golang Build
        run: make compile
